### ISSUE TITLE
Not pulling in Planned work for Sept

### ISSUE THREAD

**Issue by kent-chan-dev** [alexmerm/LTrainClosureCalendar#1]
Looks like the calendar is no longer updated for Sept and beyond.
Has anything changed in the API?

**Comment by alexmerm** [comment]
Hi! Sorry didn't see this PR. I'll look into it this week

**Comment by alexmerm** [comment]
Fixed! Had an issue with my AWS

**Comment by alexmerm** [comment]
Fixed! Had an issue with my AWS
